openapi: 3.0.0

paths:
  /users:
    post:
      summary: (tl;dr)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  example: John Doe # Property example
                email:
                  type: string
                  example: foo@bar.com # Property example
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#components/schemas/User"

    get:
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/User"

  /users/{userId}:
    get:
      summary: Get user by id
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#components/schemas/User'
    put:
      summary: Update User by id
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  example: John Doe # Property example
                email:
                  type: string
                  example: foo@bar.com # Property example       
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#components/schemas/User'
    delete:
      summary: Delete User by id
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64     
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#components/schemas/User'

components:
  schemas:
    User: # Schema name
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100 # Property example
        name:
          type: string
          example: John Doe # Property example
        email:
          type: string
          example: foo@bar.com # Property example
    post: # Schema name
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1 # Property example
        name:
          type: string
          example: New order # Property example
